mvc1/Areas/Admin/Controllers/CoverTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using bulkybook.Models;
using bulkybook.DataAccess;


namespace mvc1.Areas.Admin.Controllers
{
    public class CoverTypeController : Controller
    
    {
        private readonly AppDbContext context;

        public CoverTypeController(AppDbContext context)
        {
            this.context = context;
        }

        public async Task<ActionResult> Index()
        {
            var list = await context.Products.ToListAsync();
            return View(list);

        }
        public ActionResult Post()
        {

            return View("Post");

        }
        [HttpPost]
        [ValidateAntiForgeryToken] // csrf
        public async Task<ActionResult> Post(Product obj)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            //if (obj.Name == obj..ToString())
            //{
            //    ModelState.AddModelError("Name", "same value");
            //}

            context.Products.Add(obj);
            await context.SaveChangesAsync();
            TempData["succes"] = "created succesfully";
            return RedirectToAction("Index");
            //return View("index");

        }
        public ActionResult Edit(int? id)
        {
            Product? result = context.Products.Find(id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }
        [HttpPost]
        [ValidateAntiForgeryToken] // csrf
        public async Task<ActionResult> Edit(Product obj)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            //if (obj.Name == obj.DisplayOrder.ToString())
            //{
            //    ModelState.AddModelError("Name", "Can not be same value");
            //    return View();
            //}
            context.Products.Update(obj);
            await context.SaveChangesAsync();
            TempData["succes"] = "Edited succesfully";
            return RedirectToAction("Index");
            //return View("index");

        }
        public ActionResult Delete(int? id)
        {
            Product? result = context.Products.Find(id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }
        [HttpPost]
        [ValidateAntiForgeryToken] // csrf
        public async Task<ActionResult> Delete(Product obj)
        {
            var id = context.Products.Find(obj.Id);
            if (id == null) { return NotFound(); }
            context.Products.Remove(id);
            await context.SaveChangesAsync();
            TempData["succes"] = "Deleted succesfully";
            return RedirectToAction("Index");
            //return View("index");

        }
    }
}

mvc1/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using bulkybook.Models;
using bulkybook.DataAccess;
using Microsoft.AspNetCore.Mvc.Rendering;
using bulkybook.Models.ViewModels;

namespace mvc1.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly AppDbContext context;
        private readonly IWebHostEnvironment hostEnvironment;

        public ProductController(AppDbContext context, IWebHostEnvironment hostEnvironment)
        {
            this.context = context;
            this.hostEnvironment = hostEnvironment;
        }

        public async Task<ActionResult> Index()
        {
            var list = await context.Products.Include(u=>u.Category).ToListAsync();
            return View(list);

        }

        public ActionResult Upsert(int? id)
        {
            // id = null : create
            ProductVM productVM = new()
            {

                product = new Product(),
                CategoryList = context.Categories.ToList().Select(c =>
                new SelectListItem { Text = c.Name, Value = c.Id.ToString() }),

                CoverTypeList = context.CoverTypes.ToList().Select(c =>
                new SelectListItem { Text = c.Name, Value = c.Id.ToString() })
            };

            if (id==null||id==0)
            {
                //ViewBag.CategoryList = CategoryList;
                //ViewData["CoverTypeList"] = CoverTypeList;
                return View(productVM);
            }
            // id = not null : Edit
            else
            {
                return View(id);
            }

           

        }
        [HttpPost]
        [ValidateAntiForgeryToken] // csrf
        public async Task<ActionResult> Upsert(ProductVM obj,IFormFile? file)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
              
            var wwwRootPath = hostEnvironment.WebRootPath;//get the host environmten (wwwrootpath)
            if (file != null)
            {
                var upload=Path.Combine(wwwRootPath,"Images/Products"); // the path to upload
                string fileName=Guid.NewGuid().ToString(); //unique identifier
                var extension = Path.GetExtension(file.FileName); //gets the extension from the file name uploaded

                using (var filestream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                {
                    file.CopyTo(filestream);
                }
                obj.product.ImgUrl = "/images/products/" + fileName + extension; 
                        
            }
            context.Products.Add(obj.product);
            await context.SaveChangesAsync();
            TempData["succes"] = "Product added succesfully";
            return RedirectToAction("Index");
            //return View("index");

        }
        public ActionResult Delete(int? id)
        {
            CoverType? result = context.CoverTypes.Find(id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }
        [HttpPost]
        [ValidateAntiForgeryToken] // csrf
        public async Task<ActionResult> Delete(CoverType obj)
        {
            var id = context.CoverTypes.Find(obj.Id);
            if (id == null) { return NotFound(); }
            context.CoverTypes.Remove(id);
            await context.SaveChangesAsync();
            TempData["succes"] = "Deleted succesfully";
            return RedirectToAction("Index");
            //return View("index");

        }
    }
}

mvc1/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mvc1.Models;

namespace mvc1.Controllers
{
    public class CategoryController : Controller
    {
        private readonly AppDbContext context;

        public CategoryController(AppDbContext context)
        {
            this.context = context;
        }

        public async Task<ActionResult> Index()
        {
            var list = await context.Categories.ToListAsync();
            return View(list);

        }
        public ActionResult Post()
        {

            return View("Post");

        }
        [HttpPost]
        [ValidateAntiForgeryToken] // csrf
        public async Task<ActionResult> Post(Category obj)
        {
           if(!ModelState.IsValid)
            {
                return View();
            }
            if (obj.Name == obj.DisplayOrder.ToString()) 
            {
                ModelState.AddModelError("Name", "same value");
            }

            context.Categories.Add(obj);
            await context.SaveChangesAsync();
            TempData["succes"] ="created succesfully";
            return RedirectToAction("Index");
            //return View("index");

        }
        public ActionResult Edit(int? id)
        {
            Category? result =context.Categories.Find(id);
            if (result==null)
            {
                return NotFound();
            }
            return View(result);
        }
        [HttpPost]
        [ValidateAntiForgeryToken] // csrf
        public async Task<ActionResult> Edit(Category obj)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("Name", "Can not be same value");
                return View();
            }
            context.Categories.Update(obj);
            await context.SaveChangesAsync();
            TempData["succes"] = "Edited succesfully";
            return RedirectToAction("Index");
            //return View("index");

        }
        public ActionResult Delete(int? id)
        {
            Category? result = context.Categories.Find(id);
            if (result == null)
            {
                return NotFound();
            }
            return View(result);
        }
        [HttpPost]
        [ValidateAntiForgeryToken] // csrf
        public async Task<ActionResult> Delete(Category obj)
        {
            var id = context.Categories.Find(obj.Id);
            if (id == null) { return NotFound(); }
            context.Categories.Remove(id);
            await context.SaveChangesAsync();
            TempData["succes"] = "Deleted succesfully";
            return RedirectToAction("Index");
            //return View("index");

        }
    }
}

mvc1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc1</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/Bootswatch.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvc1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary  box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvc1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                      
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-secondary " data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">Content Managment</a>
                            <div class="dropdown-menu " data-bs-popper="static">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification"></partial>
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2023 - mvc1 -
            @*<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

mvc1/Views/Shared/_Notification.cshtml
@if(TempData["succes"] != null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script >
        
        toastr.success('@TempData["succes"]');
    </script>
    @*<h3 class="text-success">@toastr.success(TempData["succes"])</h3>*@
}